services:
  app:
    build: .
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN:?}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-info}"
      POSTGRES_DSN: "postgresql://postgres:postgres@postgres:5432/main"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
