services:
  app:
    build: .
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN:?}"
      NOTION_TOKEN: "${NOTION_TOKEN:?}"
      NOTION_DATABASE_ID: "${NOTION_DATABASE_ID:?}"
      S3_DSN: "${S3_DSN:?}"
      S3_PUBLIC_URL: "${S3_PUBLIC_URL:?}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-info}"
      POSTGRES_DSN: "postgresql://postgres:postgres@postgres:5432/main"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
